"""Ads: add hash_id.

Revision ID: db7c9165d2d8
Revises: 63856db58b96
Create Date: 2023-12-01 18:02:50.893771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7c9165d2d8'
down_revision: Union[str, None] = '63856db58b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('hash_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ads_hash_id'), 'ads', ['hash_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_hash_id'), table_name='ads')
    op.drop_column('ads', 'hash_id')
    # ### end Alembic commands ###
